name: HACS Action

on:
  push:
    branches: [main, beta]
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v6"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
          ignore: "brands"
